config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
    root 'welcomes#index'
    get "/checkout" => "welcomes#checkout_page", as: "checkout"
    post "/make_payment" => "welcomes#make_payment", as: "make_payment"
    post "/check_payment_status/:id" => "welcomes#check_payment_status"

    post "/await_payment_response_backend/:id" => "welcomes#await_payment_response_backend", as: "await_payment_response_backend"
    get "/await_payment_response/:id" => "welcomes#await_payment_response", as: "await_payment_response"
    get "/payment_response_success/:id" => "welcomes#payment_response_success", as: "payment_response_success"
    get "/payment_response_fail/:id" => "welcomes#payment_response_fail", as: "payment_response_fail"

    post "/await_payment_response_redirect/:id" => "welcomes#await_payment_response_redirect"
    post "/payment_response_success_redirect/:id" => "welcomes#payment_response_success_redirect"
    post "/payment_response_fail_redirect/:id" => "welcomes#payment_response_fail_redirect"


    resources :payments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
    enum payment_status: [:unknown, :success, :failure, :pending]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:payment_status, :details)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
    before_action :set_payment, except: [:index, :checkout_page, :make_payment]
    skip_before_action :verify_authenticity_token, :only => [:await_payment_response_backend, :await_payment_response_redirect, :payment_response_success_redirect, :payment_response_fail_redirect]
    before_action :set_api

    def index        
    end

    def checkout_page
        @payment = Payment.create()
        @amount = params[:amount]

        @callback_url = "https://eghl-test.herokuapp.com/await_payment_response_backend/#{@payment.id}"
        @return_url = "https://eghl-test.herokuapp.com/await_payment_response/#{@payment.id}" # if cancel payment
        @approval_url = "https://eghl-test.herokuapp.com/payment_response_success_redirect/#{@payment.id}"
        @unapproval_url = "https://eghl-test.herokuapp.com/payment_response_fail_redirect/#{@payment.id}"
        @timeout = 780

        @payment_id = "TEST#{Time.now.strftime('%d%m%Y%H%M%S')}"
        @hashval = Digest::SHA2.hexdigest("#{@api_pass}#{@api_id}#{@payment_id}#{@return_url}#{@approval_url}#{@unapproval_url}#{@callback_url}#{@amount}MYR192.168.2.35#{@timeout}")
    end

    def make_payment
        @payment = Payment.create()
        @amount = params[:amount]

        @callback_url = "https://eghl-test.herokuapp.com/await_payment_response_backend/#{@payment.id}"
        @return_url = "https://eghl-test.herokuapp.com/await_payment_response_redirect/#{@payment.id}"
        @approval_url = "https://eghl-test.herokuapp.com/payment_response_success_redirect/#{@payment.id}"
        @unapproval_url = "https://eghl-test.herokuapp.com/payment_response_fail_redirect/#{@payment.id}"
        @payment_id = "TEST#{Time.now.strftime('%d%m%Y%H%M%S')}"
        @timeout = 780
        
        @hashval = Digest::SHA2.hexdigest("#{@api_pass}#{@api_id}#{@payment_id}#{@return_url}#{@approval_url}#{@unapproval_url}#{@callback_url}#{@amount}MYR192.168.2.35#{@timeout}")
        req = Faraday.new do |f|
            f.adapter :net_http
        end
        
        req = req.post(
            "https://test2pay.ghl.com/IPGSG/Payment.aspx", 
            "TransactionType=SALE&PymtMethod=ANY&ServiceID=#{@api_id}&PaymentID=#{@payment_id}&OrderNumber=#{@payment_id}&PaymentDesc=-&MerchantName=Test&MerchantApprovalURL=#{@approval_url}&MerchantUnApprovalURL=#{@unapproval_url}&MerchantCallbackURL=#{@callback_url}&MerchantReturnURL=#{@return_url}&Amount=#{@amount}&CurrencyCode=MYR&CustIP=192.168.2.35&CustName=-&CustEmail=kliwaru@gmail.com&CustPhone=0173221955&HashValue=#{@hashval}&LanguageCode=en&PageTimeout=#{@timeout}"
        )
        puts "==============================================================="
        puts req
        
        if req.status == 200
            puts "==============================================================="
            puts req.status
            puts "\n\n\n"
            puts req.headers
            puts "\n\n\n"
            # puts req.body
            puts "\n\n\n"
            render inline: req.body
        else
            notice = "SOMETHING WENT WRONG!"
            redirect_to root_path
        end
    end

    # callback_url for billplz
    def await_payment_response_backend 
        puts params
        @payment.update(details: params)
        if params["TxnStatus"] == "0"
            @payment.update(payment_status: "success")
        elsif params["TxnStatus"] == "1"
            @payment.update(payment_status: "failure")
        elsif params["TxnStatus"] == "2"
            @payment.update(payment_status: "pending")
        end
    end

    # redirect url
    def await_payment_response
    end

    # from frontend AJAX
    def check_payment_status
        render :json => { status: @payment.payment_status }
    end

    def payment_response_success
    end

    def payment_response_fail
    end

    def await_payment_response_redirect
        puts params
        redirect_to await_payment_response_path(@payment)
    end
    
    def payment_response_success_redirect
        # redirect only if success else
        puts params
        redirect_to payment_response_success_path(@payment)
    end

    def payment_response_fail_redirect
        # redirect only if fail else
        puts params
        redirect_to payment_response_fail_path(@payment)
    end


    private
    def set_payment
        @payment = Payment.find(params[:id])
    end

    def set_api
        @api_id = "sit"
        @api_pass = "sit12345"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eghl Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, user-scalable=yes">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <br><br><br>
    <hr>
    <%= link_to "Home", root_path %><br>
    <%= link_to "Payment Index", payments_path %><br>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :payment_status %>
    <%= form.number_field :payment_status %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
        <th>ID</th>
      <th>Payment status</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.id %></td>
        <td><%= payment.payment_status %></td>
        <td><%= payment.details %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment status:</strong>
  <%= @payment.payment_status %>
</p>

<p>
  <strong>Details:</strong>
  <%= @payment.details %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/welcomes/await_payment_response.html.erb
<h1>Await Payment Response</h1>
<h3>Bill ID: <%= @payment.id %></h3>

<div>
    <i>View Order Summaries</i>
    <p>blabla..</p>
    <p>blabla..</p>
    <p>blabla..</p>
</div>


<script>
    function checkPaymentStatus(id) {
        $.ajax({
            url: `/check_payment_status/${id}`,
            method: "POST",
            success: function(result){
                console.log('Check Payment Status ' + Date(Date.now()).toString());
                console.log(result["status"]);

                if (result["status"] == "success") {
                    location.replace(`/payment_response_success/${id}`);
                } else if (result["status"] == "failure") {
                    location.replace(`/payment_response_fail/${id}`);
                } else if (result["status"] == "pending") {
                    location.replace(`/payment_response_fail/${id}`);
                } else {
                    setTimeout(() => {
                        checkPaymentStatus(id);
                    }, 2000);
                }
            },
            error: function(error){
                console.log('Loop fail');
                console.log(error);
            }
        });
    }

    $(document).ready(() => {
        checkPaymentStatus(<%= @payment.id %>);
    });
</script>

app/views/welcomes/checkout_page.html.erb
<h1>Checkout Page</h1>

<div>
    <i>View Order Summaries</i>
    <p>blabla..</p>
    <p>blabla..</p>
    <p>blabla..</p>
</div>
<br>
<%#= button_to "Make Payment", make_payment_path, params: {amount: @amount} %>


<hr>
<form name="frmPayment" method="post" action="https://test2pay.ghl.com/IPGSG/Payment.aspx">
    <input type="text" name="TransactionType" value="SALE">
    <input type="text" name="PymtMethod" value="ANY">
    <input type="text" name="ServiceID" value="<%= @api_id %>">
    <input type="text" name="PaymentID" value="<%= @payment_id %>">
    <input type="text" name="OrderNumber" value="<%= @payment_id %>">
    <input type="text" name="PaymentDesc" value="Booking No: IJKLMN, Sector: KUL-BKI, First Flight Date: 26 Sep 2012">
    <input type="text" name="MerchantName" value="Merchant A">
    <input type="text" name="MerchantApprovalURL" value="<%= @approval_url %>">
    <input type="text" name="MerchantUnApprovalURL" value="<%= @unapproval_url %>">
    <input type="text" name="MerchantCallBackURL" value="<%= @callback_url %>">
    <input type="text" name="MerchantReturnURL" value="<%= @return_url %>">
    <input type="text" name="Amount" value="<%= @amount %>">
    <input type="text" name="CurrencyCode" value="MYR">
    <input type="text" name="CustIP" value="192.168.2.35">
    <input type="text" name="CustName" value="Jason">
    <input type="text" name="CustEmail" value="Jasonabc@gmail.com">
    <input type="text" name="CustPhone" value="60121235678">
    <input type="text" name="HashValue" value="<%= @hashval %>">
    <input type="text" name="LanguageCode" value="en">
    <input type="text" name="PageTimeout" value="<%= @timeout %>">
    <input type="submit">
</form>

app/views/welcomes/index.html.erb
<h1>EGHL Test</h1>

<%= form_with url: checkout_path, method: :get, local: true do |f| %>
    <%= f.text_field :amount %>
    <%= f.submit "Checkout" %>
<% end %>
<storng>Amount must be 0.00</storng>

<br><br>
<h3>Payment Flow</h3>

<p>
    <strong>User Clicks "Checkout Cart"</strong>
    <br>GET welcomes#checkout_page
    <br>Controller creates new payment with order details
    <br>User redirected to checkout page to confirm order details & make payment
</p>

<p>
    <strong>User clicks "Make Payment"</strong>
    <br>Passes to Billplz handling
</p>

<div class="two columns">
    <div>
        <p>
            <strong>User makes Payment w Billplz</strong>
            <br>Billplz communicates with my backend
            <br>GET welcomes#await_payment_response_backend    
        </p>
    </div>
    <div>
        <p>
            <strong>User redirected to "Await payment response" page</strong>
            <br>GET welcomes#await_payment_response to update bill payment status
            <br>on page load, Recursive JS runs AJAX to check backend of payment status update to determine redirect
            <br>AJAX Calls to welcomes#check_payment_status
        </p>
    </div>
</div>

<div class="two columns">
    <div>
        <strong>Payment Success</strong>
    </div>
    <div>
        <strong>Payment Error</strong>
    </div>
</div>

app/views/welcomes/payment_response_fail.html.erb
<h1>Payment Response FAIL</h1>

<div>
    <%= @response %>
</div>

<br><br>
<%= button_to "Try Payment Again", payment_path %>

<br><br>
<%= link_to "Home", root_path %>

app/views/welcomes/payment_response_success.html.erb
<h1>Payment Response SUCCESS</h1>

<div>
    <%= @response %>
</div>

<br><br>
<%= link_to "Home", root_path %>